[units]

acceleration = "m / s ** 2"
angle = "radian"
angular_momentum = "kg * m ** 2 / s"
angular_momentum_specific = "m ** 2 / s"
density = "kg / m ** 3"
dimensionless = "dimensionless"
energy = "joule"
energy_specific = "joule / kg"
entropy = "joule / kelvin"
force = "newton"
frequency = "hertz"
length = "m"
magnetic_field = "tesla"
mass = "kg"
momentum = "kg * m / s"
power = "watt"
pressure = "pascal"
temperature = "kelvin"
time = "s"
velocity = "m / s"

[arrays]

accretion_radius = "length"
alpha_viscosity_numerical = "dimensionless"
angular_momentum = "angular_momentum"
angular_velocity = "velocity"
azimuthal_angle = "angle"
density = "density"
differential_velocity = "velocity"
dust_density = "density"
dust_fraction = "dimensionless"
dust_mass = "mass"
dust_to_gas_ratio = "dimensionless"
eccentricity = "dimensionless"
gas_density = "density"
gas_fraction = "dimensionless"
gas_mass = "mass"
gravitational_potential = "energy"
inclination = "angle"
internal_energy = "energy_specific"
keplerian_frequency = "frequency"
kinetic_energy = "energy"
last_injection_time = "time"
magnetic_field = "magnetic_field"
mass = "mass"
mass_accreted = "mass"
momentum = "momentum"
polar_angle = "angle"
position = "length"
pressure = "pressure"
projection = "length"
radius_cylindrical = "length"
radius_spherical = "length"
semi_major_axis = "length"
smoothing_length = "length"
softening_radius = "length"
sound_speed = "velocity"
specific_angular_momentum = "angular_momentum_specific"
specific_kinetic_energy = "energy_specific"
spin = "angular_momentum"
stokes_number = "dimensionless"
stopping_time = "time"
sub_type = "dimensionless"
temperature = "temperature"
timestep = "time"
type = "dimensionless"
velocity = "velocity"
velocity_divergence = "frequency"
velocity_radial_cylindrical = "velocity"
velocity_radial_spherical = "velocity"
vorticity = "frequency"
