[units]

acceleration = "m / s ** 2"
angle = "radian"
angular_momentum = "kg * m ** 2 / s"
angular_momentum_specific = "m ** 2 / s"
density = "kg / m ** 3"
dimensionless = "dimensionless"
energy = "joule"
energy_specific = "joule / kg"
entropy = "joule / kelvin"
force = "newton"
frequency = "hertz"
length = "m"
magnetic_field = "tesla"
mass = "kg"
momentum = "kg * m / s"
power = "watt"
pressure = "pascal"
temperature = "kelvin"
time = "s"
velocity = "m / s"

[arrays]

accretion_radius = "length: 1"
alpha_viscosity_numerical = ""
angular_momentum = "mass: 1, length: 2, time: -1"
angular_velocity = "length: 1, time: -1"
azimuthal_angle = "angle: 1"
density = "mass: 1, length: -3"
differential_velocity = "length: 1, time: -1"
dust_density = "mass: 1, length: -3"
dust_fraction = ""
dust_mass = "mass: 1"
dust_to_gas_ratio = ""
eccentricity = ""
gas_density = "mass: 1, length: -3"
gas_fraction = ""
gas_mass = "mass: 1"
gravitational_potential = "mass: 1, length: 2, time: -2"
inclination = "angle: 1"
internal_energy = "length: 2, time: -2"
keplerian_frequency = "time: -1"
kinetic_energy = "mass: 1, length: 2, time: -2"
last_injection_time = "time: 1"
luminosity = "mass: 1, length: 2, time: -3"
magnetic_field = "mass: 1, time: -2, current: -1"
mass = "mass: 1"
mass_accreted = "mass: 1"
mass_loss_rate = "mass: 1, time: -1"
momentum = "mass: 1, length: 1, time: -1"
polar_angle = "angle: 1"
position = "length: 1"
pressure = "mass: 1, length: -1, time: -2"
projection = "length: 1"
radius_cylindrical = "length: 1"
radius_spherical = "length: 1"
semi_major_axis = "length: 1"
smoothing_length = "length: 1"
softening_radius = "length: 1"
sound_speed = "length: 1, time: -1"
specific_angular_momentum = "length: 2, time: -1"
specific_kinetic_energy = "length: 2, time: -2"
spin = "mass: 1, length: 2, time: -1"
stokes_number = ""
stopping_time = "time: 1"
sub_type = ""
temperature = "temperature: 1"
timestep = "time: 1"
type = ""
velocity = "length: 1, time: -1"
velocity_divergence = "time: -1"
velocity_radial_cylindrical = "length: 1, time: -1"
velocity_radial_spherical = "length: 1, time: -1"
vorticity = "time: -1"
